### ISSUE TITLE
no such attribute: chanType

### ISSUE THREAD

**Issue by mattunlv** [mattunlv/ProcessJ-Compiler#12]
import std.io;

public proc void main(string args[]) {
    do {
      break;
    } while (true);
    int a = 9;

}

import std.io;

public proc void main(string args[]) {
    do {
      break;
    } while (true);
    int a = 9;

}

**Comment by mattunlv** [comment]
oops:

darkwing:ProcessJ matt$ pjc test4.pj
WORKING DIR IS /Users/matt/.processj
Exception in thread "main" java.lang.IllegalArgumentException: no such attribute: chanType
	at org.stringtemplate.v4.ST.add(ST.java:223)
	at CodeGeneratorJava.CodeGeneratorJava.visitLocalDecl(CodeGeneratorJava.java:1305)
	at AST.LocalDecl.visit(LocalDecl.java:32)
	at CodeGeneratorJava.CodeGeneratorJava.visitSequence(CodeGeneratorJava.java:1890)
	at AST.Sequence.visit(Sequence.java:58)
	at CodeGeneratorJava.CodeGeneratorJava.visitBlock(CodeGeneratorJava.java:1015)
	at AST.Block.visit(Block.java:14)
	at CodeGeneratorJava.CodeGeneratorJava.visitProcTypeDecl(CodeGeneratorJava.java:1652)
	at AST.ProcTypeDecl.visit(ProcTypeDecl.java:42)
	at CodeGeneratorJava.CodeGeneratorJava.visitSequence(CodeGeneratorJava.java:1890)
	at AST.Sequence.visit(Sequence.java:58)
	at CodeGeneratorJava.CodeGeneratorJava.visitCompilation(CodeGeneratorJava.java:622)
	at AST.Compilation.visit(Compilation.java:23)
	at ProcessJc.generateCodeJava(ProcessJc.java:213)
	at ProcessJc.main(ProcessJc.java:192)
